backend:
  name: git-gateway
  branch: main
  site_url: https://dymiec.com.mx

media_folder: "images"
public_folder: "/images"

collections:
  - name: "contenido"
    label: "Contenido del sitio"
    files:
      - label: "Inicio"
        name: "inicio"
        file: "index.html"
        fields:
          - { label: "TÃ­tulo", name: "title", widget: "string" }
          - { label: "Contenido principal", name: "body", widget: "markdown" }